products = [
    {
        'id': '1',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 0,
        'rating': 2.3,
        'reviews': 443
    },
    {
        'id': '2',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 2.3,
        'reviews': 443
    },
    {
        'id': '3',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 2.3,
        'reviews': 443
    },
    {
        'id': '4',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 2.3,
        'reviews': 443
    },
    {
        'id': '5',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '6',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '7',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '8',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '9',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '10',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '11',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '12',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '13',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '14',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '15',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
    {
        'id': '16',
        'name': 'VOID RGB ELITE Wireless Premium Gaming Headset',
        'image': '/images/sample.jpg',
        'desc': 'Immerse yourself in the action with the CORSAIR VOID RGB ELITE Wireless, boasting custom-tuned 50mm neodymium audio drivers, comfortable microfiber mesh fabric with memory foam earpads, and a 2.4GHz wireless connection.',
        'brand': 'Corsair',
        'category': 'Headsets',
        'price': 79.99,
        'stockcount': 22,
        'rating': 4.6,
        'reviews': 443
    },
]
