# Generated by Django 3.2.4 on 2021-07-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210710_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reviews',
            new_name='numReviews',
        ),
    ]
